In [ ]:
#Задание 1. Загрузка данных
"""
Изучить представленный набор данных на основе описания его столбцов, загрузить его и оставить 8 столбцов 
для дальнейшего изучения: 
surgery?, Age, rectal temperature, pulse, respiratory rate, 
temperature of extremities, pain, outcome.

"""

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("horse_data.csv", na_values = "?")
df.head(1)

2  1  530101  38.50    66    28   3  3.1    ?  2.1  ...  45.00  8.40  \
0  1.0  1  534817   39.2  88.0  20.0 NaN  NaN  4.0  1.0  ...   50.0  85.0   

   ?.4  ?.5  2.2  2.3  11300  00000  00000.1  2.4  
0  2.0  2.0  3.0    2   2208      0        0    2  

[1 rows x 28 columns]

In [3]:
# Переименовываю столбцы

need_list = ["surgery?", "Age", "rectal temperature", "pulse", "respiratory rate", "temperature of extremities", "pain", "outcome"]

new_data = df.rename({'2':'surgery?','1':'Age','530101':'Hospital Numbe','38.50':'rectal temperature','66':'pulse',
                      '28':'respiratory rate','3':'temperature of extremities','3.1':'peripheral pulse','?':'mucous membranes',
                      '2.1':'capillary refill time','5':'pain','4':'peristalsis','4.1':'abdominal distension','?.1':'nasogastric tube',
                      '?.2':'nasogastric reflux','?.3':'nasogastric reflux PH','3.2':'rectal examination','5.1':'abdomen',
                      '45.00':'packed cell volume','8.40':'total protein','?.4':'abdominocentesis appearance','?.5':'abdomcentesis total protein',
                      '2.2':'outcome','2.3':'surgical lesion?','11300':'type of lesion','00000':'type of lesion','00000.1':'type of lesion',
                      '2.4':'cp_data'}

, axis =1)

# оставляю только нужные
new_data = new_data.loc[:, new_data.columns.isin(need_list)]
new_data.head(10)


surgery?  Age  rectal temperature  pulse  respiratory rate  \
0       1.0    1                39.2   88.0              20.0   
1       2.0    1                38.3   40.0              24.0   
2       1.0    9                39.1  164.0              84.0   
3       2.0    1                37.3  104.0              35.0   
4       2.0    1                 NaN    NaN               NaN   
5       1.0    1                37.9   48.0              16.0   
6       1.0    1                 NaN   60.0               NaN   
7       2.0    1                 NaN   80.0              36.0   
8       2.0    9                38.3   90.0               NaN   
9       1.0    1                38.1   66.0              12.0   

   temperature of extremities  pain  outcome  
0                         NaN   3.0      3.0  
1                         1.0   3.0      1.0  
2                         4.0   2.0      2.0  
3                         NaN   NaN      2.0  
4                         2.0   2.0      1.0  
5                         1.0   3.0      1.0  
6                         3.0   NaN      2.0  
7                         3.0   4.0      3.0  
8                         1.0   5.0      1.0  
9                         3.0   3.0      1.0

In [4]:
names = list(new_data.columns.values)
names

['surgery?',
 'Age',
 'rectal temperature',
 'pulse',
 'respiratory rate',
 'temperature of extremities',
 'pain',
 'outcome']

In [ ]:
#Задание 2. Первичное изучение данных
"""
Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы
"""

In [5]:
# расчет базовой статистики 

new_data.describe()

surgery?        Age  rectal temperature       pulse  \
count  298.000000  299.00000          239.000000  275.000000   
mean     1.395973    1.64214           38.166527   71.934545   
std      0.489881    2.17730            0.733508   28.680522   
min      1.000000    1.00000           35.400000   30.000000   
25%      1.000000    1.00000           37.800000   48.000000   
50%      1.000000    1.00000           38.200000   64.000000   
75%      2.000000    1.00000           38.500000   88.000000   
max      2.000000    9.00000           40.800000  184.000000   

       respiratory rate  temperature of extremities        pain     outcome  
count        241.000000                  243.000000  244.000000  298.000000  
mean          30.427386                    2.345679    2.942623    1.550336  
std           17.678256                    1.046369    1.303993    0.737967  
min            8.000000                    1.000000    1.000000    1.000000  
25%           18.000000                    1.000000    2.000000    1.000000  
50%           24.000000                    3.000000    3.000000    1.000000  
75%           36.000000                    3.000000    4.000000    2.000000  
max           96.000000                    4.000000    5.000000    3.000000

In [6]:
# Нахожу выбросы через межквартильный размах
q1 = new_data.quantile(0.25)
q3 =  new_data.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upperr_bound = q3 - (1.5 * iqr)

outliers = new_data[(new_data < lower_bound) | (new_data > upperr_bound)]
#outliers.head(100)
#outliers.describe()

In [ ]:
#Задание 3. Работа с пропусками
"""
Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе заполнения пропусков 
по каждому столбцу на основе рассчитанных статистик и возможной взаимосвязи значений в них. 
Сформировать датафрейм, в котором пропуски будут отсутствовать.
"""

In [7]:
new_data["Age"].unique()

array([1, 9], dtype=int64)

In [8]:
print(new_data.groupby("Age")["pulse"].median())

Age
1     60.0
9    124.0
Name: pulse, dtype: float64


In [9]:
#Расчитываю сколько пропусков всего
(new_data.isna().mean() * 100).round(2)

surgery?                       0.33
Age                            0.00
rectal temperature            20.07
pulse                          8.03
respiratory rate              19.40
temperature of extremities    18.73
pain                          18.39
outcome                        0.33
dtype: float64

In [ ]:
"""
1. surgery и outcome имеют меньше 0,5% пропусков из общего массива. Можно заменить модой
2. pulse имеет 8% пропусков. Ст отклонение достаточно большое. нужно тогда брать медиану. Будем считать, что возврас влияет
3. rectal temperature, respiratory rate, temperature of extremities, pain  очень много пропусков. 
Будем считать, что возврас влияет и хирургия. Берем медиану
"""

In [10]:
without_nan_data = new_data
without_nan_data["surgery?"].fillna(without_nan_data["surgery?"].mode()[0], inplace = True)

without_nan_data["surgery?"].value_counts()

1.0    180
2.0    118
Name: surgery?, dtype: int64

In [11]:
without_nan_data["surgery?"].unique()

array([ 1.,  2., nan])

In [36]:
#Меняю проруски по правилам выше
first_point = ["surgery?", "outcome"]
new_data["outcome"].fillna(new_data["outcome"].mode()[0], inplace = True)  
new_data["surgery?"].fillna(new_data["surgery?"].mode()[0], inplace = True)
new_data["pulse"].fillna(new_data.groupby("Age")["pulse"].transform("median"), inplace = True)
new_data["rectal temperature"].fillna(new_data.groupby(["Age", "surgery?"])["rectal temperature"].transform("median"), inplace = True)
new_data["temperature of extremities"].fillna(new_data.groupby(["Age", "surgery?"])["temperature of extremities"].transform("median"), inplace = True)
new_data["pain"].fillna(new_data.groupby(["Age", "surgery?"])["pain"].transform("median"), inplace = True)
new_data["respiratory rate"].fillna(new_data.groupby(["Age", "surgery?"])["respiratory rate"].transform("median"), inplace = True)



new_data["respiratory rate"].unique()
#new_data["pulse"].value_counts()


array([20., 24., 84., 35., 16., 36., 30., 12., 52., 28., 48., 21., 60.,
       34., 42., 96., 72., 15., 44., 32., 22., 18., 80., 40., 10., 51.,
       68., 66.,  9., 14., 90.,  8., 23., 58., 13., 70., 26., 88., 25.,
       50.])

In [38]:
(new_data.isna().mean() * 100).round(2)

surgery?                      0.0
Age                           0.0
rectal temperature            0.0
pulse                         0.0
respiratory rate              0.0
temperature of extremities    0.0
pain                          0.0
outcome                       0.0
dtype: float64