In [ ]:
#Задание 1
'''
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
'''

In [1]:
import numpy as np

In [305]:
n = int(10)

In [306]:
array_list = -np.sort(-np.arange(0,n))
array_list

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Задание 2
'''
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
'''

In [189]:
matrix_task = np.diag(array_list)
matrix_task

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [190]:
count_1 = 0
for i in matrix_task:
    count_1 += i
print(sum(count_1))

45


In [179]:
#Задание 3
"""

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""

In [186]:
from numpy import linalg

In [218]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
"""
x = 0.46666667
y = 3.84444444
z = -5.55555556
"""

In [209]:
k = np.array( [ [1, 3], [2, -4] ] )
v = b = np.array( [9, 8] )
linalg.solve(k, v)

array([6., 1.])

In [180]:
# Задание 4
'''
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
'''

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [3]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [4]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [5]:
cosine(users_stats[1], next_user_stats)

0.8451542547285165

In [173]:
work_list = []
work_list_2 = []
for user_vector in users_stats:
    result_cos = cosine(user_vector, next_user_stats)
    work_list = np.append(work_list, result_cos)
    max_cos = np.max(work_list)
    print(result_cos)
    
    
    
print(max_cos)

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
0.9486832980505138


In [176]:
for answer in users_stats:
    result_cos_2 = cosine(answer, next_user_stats)
    if max_cos == result_cos_2:
        print(answer)

[0 1 1 0 0 0]
